name: Statix Check
on:
  push:
jobs:
  statix-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v19
        with:
          extra-conf: |
            extra-experimental-features = flakes nix-command recursive-nix pipe-operators
      - name: Check OS build
        shell: bash
        run: |
          echo "Fixes using *statix*" >> /tmp/message-boy
          nix run nixpkgs#statix -- check --format stderr >> /tmp/message-body
          nix run nixpkgs#statix -- fix .
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "lint: statix fixes"
          delete-branch: true
          body-path: /tmp/message-body
