name: "Update Flake Packages ❄️"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5"
jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v19
        with:
          extra-conf: |
            extra-experimental-features = flakes nix-command recursive-nix pipe-operators
      - run: find . -regextype posix-extended -name '**.nix' -and -not -name 'flake.nix' -and -not -path '**secrets**' -exec nix run nixpkgs#update-nix-fetchgit -- -v {} \+
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: create-pr
        with:
          commit-message: automated package update
          body: |
            Updated packages using *update-nix-fetchgit*
      - name: Enable auto merge created PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr merge --auto --squash ${{ steps.create-pr.outputs.pull-request-number }} || true
